image: node:12.16.1-alpine

pipelines:
  custom:
    # Deploy to test
    deploy-to-test:
      - step:
          name: Deploy to test
          deployment: Test
          caches:
            - node
          script:
            - yarn install --production=false
            - scripts/deploy/run.sh
          services:
          - docker




